#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2023 Aurélien Gâteau <mail@agateau.com>
#
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail

PROGNAME=$(basename $0)

DL_URL_TEMPLATE="https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=@FF_LANG@"
README_URL="https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest/README.txt"

TEMP_DIR="$(mktemp --tmpdir -d "tmfi-XXXXXX")"
cleanup() {
    rm -rf $TEMP_DIR
}

# XDG directories
CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}
SHARE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"
BIN_DIR="$HOME/.local/bin"

# ANSI colors
C_YELLOW="\e[33m"
C_CYAN="\e[36m"
C_RESET="\e[0m"

# Default values
DEFAULT_DEST_DIR="$CACHE_DIR/firefox"
FF_LANG=en-US

die() {
    echo "$PROGNAME: $*" >&2
    exit 1
}

usage() {
    if [ "$*" != "" ] ; then
        echo "Error: $*"
        echo
    fi

    echo -e "
Usage: $PROGNAME [OPTION ...] [<dest_dir>]
Installs Firefox and create desktop menu entries.

Options:
  -h, --help          display this usage message and exit.
  -l, --lang LANG     install for language LANG.
  --lang-list         print the list of supported languages [1].

[1]: This command downloads and print the content of
${C_CYAN}${README_URL}${C_RESET}.
"

    exit 1
}

h1() {
    echo -e "${C_YELLOW}$*${C_RESET}"
    echo
}

while [ $# -gt 0 ] ; do
    case "$1" in
    -h|--help)
        usage
        ;;
    -l|--lang)
        FF_LANG="$2"
        shift
        ;;
    --lang-list)
        exec curl -s "${README_URL}"
        ;;
    -*)
        usage "Unknown option '$1'"
        ;;
    *)
        if [ -z "$DEST_DIR" ] ; then
            DEST_DIR="$1"
        else
            usage "Too many arguments"
        fi
        ;;
    esac
    shift
done

if [ -z "${DEST_DIR:-}" ] ; then
    DEST_DIR="$DEFAULT_DEST_DIR"
fi

DL_URL=$(echo $DL_URL_TEMPLATE | sed "s/@FF_LANG@/$FF_LANG/")

DL_PATH="$TEMP_DIR/firefox-$FF_LANG.tar.bz2"

h1 "🦊 Summary"
echo -e "Firefox will be installed in $C_CYAN$DEST_DIR$C_RESET.
A ${C_YELLOW}firefox$C_RESET symbolic link will be installed in $C_CYAN$BIN_DIR$C_RESET.
A Firefox menu entry will be installed in $C_CYAN$SHARE_DIR$C_RESET.

Make sure $C_CYAN$BIN_DIR$C_RESET is in \$PATH!
"
echo -n "Continue (y/N)? "
read answer

if [ "$answer" != "y" ] ; then
    exit 1
fi
echo

h1 "🦊 Downloading Firefox from\n${C_CYAN}$DL_URL"
curl --location "$DL_URL" --output "$DL_PATH"
echo

h1 "🦊 Unpacking"
mkdir -p "$DEST_DIR"
tar -C "$DEST_DIR" --strip-components 1 -xf "$DL_PATH"

h1 "🦊 Creating symbolic link in $BIN_DIR"
mkdir -p "$BIN_DIR"
rm -f "$BIN_DIR/firefox"
ln -s "$DEST_DIR/firefox" "$BIN_DIR"

h1 "🦊 Creating menu entries"
mkdir -p "$SHARE_DIR"
cp -R share/* "$SHARE_DIR"

h1 "🎉 All done!"

echo "You can now start Firefox from the command-line or from your desktop menu."
echo

h1 "🐛 Troubleshooting"

echo -e "- If the menu entry does not appear, try restarting your desktop session.

- If Firefox does not use your existing configuration, start it from the command-line like this:

    ${C_CYAN}firefox --ProfileManager${C_RESET}

and select another profile."
